<?php
/**
 * This file has been automaticaly generated by Pomm Cli package.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Model\Db\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Users
 *
 * Structure class for relation public.users.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Users extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     * @return null
     */
    public function __construct()
    {
        $this
            ->setRelation('public.users')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('auth_name', 'varchar')
            ->addField('auth_key', 'varchar')
            ;
    }
}
